import { colorBoardProps } from "./components/ColorBoard";

export const data: colorBoardProps[] = [
  {
    bgColor: "#FFFFE5",
    textColor: "#ff858b",
    dateText: "01.01",
    colorName: "纯白",
    text1: "拥有美丽心灵",
    text2: ["纯洁", "优雅", "简约"],
  },
  {
    bgColor: "#e6eae6",
    textColor: "#95ba95",
    dateText: "01.02",
    colorName: "霜白",
    text1: "美学思索的集合体",
    text2: ["感性", "逻辑", "纯净"],
  },
  {
    bgColor: "#afafb0",
    textColor: "#ffffff",
    dateText: "01.03",
    colorName: "银灰色",
    text1: "高尚的心灵",
    text2: ["勇气", "平和", "经营力"],
  },
  {
    bgColor: "#8d9192",
    textColor: "#ebec90",
    dateText: "01.04",
    colorName: "铝灰",
    text1: "无畏开朗的挑战者",
    text2: ["开朗", "正能量"],
  },
  {
    bgColor: "#736d71",
    textColor: "#ff8f7f",
    dateText: "01.05",
    colorName: "钢灰",
    text1: "快速而强大的人",
    text2: ["直觉", "洞察力", "潜力"],
  },
  {
    bgColor: "#705b67",
    textColor: "#64bcb3",
    dateText: "01.06",
    colorName: "葡萄鼠",
    text1: "戏剧性生活的实践者",
    text2: ["论理心", "速度", "冒险"],
  },
  {
    bgColor: "#0d0015",
    textColor: "#ffffff",
    dateText: "01.07",
    colorName: "漆黑",
    text1: "充满激情，有很多想法向目标挑战",
    text2: ["激情", "才华", "想象力"],
  },
  {
    bgColor: "#b8c43a",
    textColor: "#fff777",
    dateText: "01.08",
    colorName: "柠檬黄",
    text1: "热爱自然的抒情家",
    text2: ["宗教情绪", "宇宙构想"],
  },
  {
    bgColor: "#69821b",
    textColor: "#ffc674",
    dateText: "01.09",
    colorName: "苔藓绿",
    text1: "时常能感受到温暖的人",
    text2: ["匠心", "神秘", "想象力"],
  },
  {
    bgColor: "#7b8d42",
    textColor: "#78d3b0",
    dateText: "01.10",
    colorName: "草色",
    text1: "拥有广阔的情感世界",
    text2: ["智慧", "艺术", "精致"],
  },
  {
    bgColor: "#bdd99f",
    textColor: "#ffffff",
    dateText: "01.11",
    colorName: "雾绿",
    text1: "创造新时代的理想人物",
    text2: ["努力", "语言力", "勇气"],
  },
  {
    bgColor: "#d6e9ca",
    textColor: "#9c8e92",
    dateText: "01.12",
    colorName: "白绿",
    text1: "全力以赴的挑战者",
    text2: ["尊严", "外交", "洞察力"],
  },
  {
    bgColor: "#37a34a",
    textColor: "#fff68f",
    dateText: "01.13",
    colorName: "帕洛特绿",
    text1: "有自己生活方式的自立者",
    text2: ["语言行动力", "谦逊", "沉着冷静"],
  },
  {
    bgColor: "#7b8d44",
    textColor: "#e8c47f",
    dateText: "01.14",
    colorName: "草绿色",
    text1: "等待感情成熟的艺术家",
    text2: ["成熟", "感性"],
  },
  {
    bgColor: "#00552e",
    textColor: "#ffffff",
    dateText: "01.15",
    colorName: "深绿",
    text1: "瞳孔如星之羁绊",
    text2: ["信条", "模范", "慈爱"],
  },
  {
    bgColor: "#f0f6da",
    textColor: "#ff8697",
    dateText: "01.16",
    colorName: "白莉",
    text1: "在爱的实践中",
    text2: ["想象力", "追求自然"],
  },
  {
    bgColor: "#006e54",
    textColor: "#ffbc75",
    dateText: "01.17",
    colorName: "MOEGIIRO",
    text1: "有勇气和好奇心的美食家",
    text2: ["生活意识", "领导力", "微笑"],
  },
  {
    bgColor: "#47744b",
    textColor: "#96cd96",
    dateText: "01.18",
    colorName: "FOLIAGE",
    text1: "保持纯真少年",
    text2: ["诚实", "干练", "谦虚"],
  },
  {
    bgColor: "#9fc24d",
    textColor: "#ffffff",
    dateText: "01.19",
    colorName: "叶绿",
    text1: "坚持不懈的人",
    text2: ["温柔", "自尊", "精神"],
  },
  {
    bgColor: "#288c66",
    textColor: "#ebec90",
    dateText: "01.20",
    colorName: "森林绿",
    text1: "形象清晰者",
    text2: ["能量", "自我投资"],
  },
  {
    bgColor: "#a0d8ef",
    textColor: "#ff858b",
    dateText: "01.21",
    colorName: "天空色",
    text1: "感知美好事物的人",
    text2: ["感性", "可能性", "艺术性"],
  },
  {
    bgColor: "#00a3af",
    textColor: "#f1f49a",
    dateText: "01.22",
    colorName: "浅葱色",
    text1: "富有同情心",
    text2: ["兴奋", "爱情", "友情"],
  },
  {
    bgColor: "#38a1db",
    textColor: "#ffffff",
    dateText: "01.23",
    colorName: "露草",
    text1: "心境平和宁静",
    text2: ["年轻", "情绪", "专注力"],
  },
  {
    bgColor: "#00688b",
    textColor: "#ebec90",
    dateText: "01.24",
    colorName: "鸭羽色",
    text1: "快乐梦想的乐观者",
    text2: ["聪明", "诚实", "感性"],
  },
  {
    bgColor: "#0f2350",
    textColor: "#ff777e",
    dateText: "01.25",
    colorName: "深靛蓝",
    text1: "生活一帆风顺",
    text2: ["理想", "现实", "新生活"],
  },
  {
    bgColor: "#e3d7a3",
    textColor: "#ff9d4d",
    dateText: "01.26",
    colorName: "奶油",
    text1: "拥有太阳般的个性",
    text2: ["组织力", "机智", "表情丰富"],
  },
  {
    bgColor: "#fef400",
    textColor: "#83bc50",
    dateText: "01.27",
    colorName: "淡柠檬",
    text1: "优雅大气的人",
    text2: ["穿着", "神秘的睡眠"],
  },
  {
    bgColor: "#ffd900",
    textColor: "#ce8230",
    dateText: "01.28",
    colorName: "鸭羽色",
    text1: "天生的乐观者",
    text2: ["冒险", "开朗", "好奇心"],
  },
  {
    bgColor: "#c3d825",
    textColor: "#81a326",
    dateText: "01.29",
    colorName: "若草色",
    text1: "具有非凡说服力的人",
    text2: ["直觉", "名誉", "运动神经"],
  },
  {
    bgColor: "#529c47",
    textColor: "#fff333",
    dateText: "01.30",
    colorName: "淡柠檬",
    text1: "与动植物投缘的人",
    text2: ["充满爱", "喜爱动物"],
  },
  {
    bgColor: "#e0ebaf",
    textColor: "#fa9121",
    dateText: "01.31",
    colorName: "嫩芽色",
    text1: "脆弱的浪漫主义者",
    text2: ["感伤", "社会适应性"],
  },
  {
    bgColor: "#3f4e93",
    textColor: "#ff7c8f",
    dateText: "02.01",
    colorName: "锥花蓝",
    text1: "能得到认可的艺术家",
    text2: ["文化", "社会", "艺术"],
  },
  {
    bgColor: "#bc64a4",
    textColor: "#ffcd77",
    dateText: "02.02",
    colorName: "若紫",
    text1: "有明显差异的个性派",
    text2: ["想象力", "直觉", "敬慕"],
  },
  {
    bgColor: "#212971",
    textColor: "#ffffff",
    dateText: "02.03",
    colorName: "皇家蓝",
    text1: "明确自身价值，与生俱来的公主",
    text2: ["直觉力", "羞怯", "威严"],
  },
  {
    bgColor: "#cca6bf",
    textColor: "#ffffff",
    dateText: "02.04",
    colorName: "紫藤色",
    text1: "与众不同的个性派",
    text2: ["感性", "才气转化", "外向"],
  },
  {
    bgColor: "#503471",
    textColor: "#ff7fa6",
    dateText: "02.05",
    colorName: "堇紫花",
    text1: "明确前进道路的灵之主",
    text2: ["美丽", "神秘", "梦幻"],
  },
  {
    bgColor: "#debdd8",
    textColor: "#ffffff",
    dateText: "02.06",
    colorName: "紫丁香",
    text1: "隐藏着让人感动的力量",
    text2: ["家庭", "力量", "高贵"],
  },
  {
    bgColor: "#b269a1",
    textColor: "#ffffff",
    dateText: "02.07",
    colorName: "莫贝特",
    text1: "一心一意且有使命感",
    text2: ["自主", "天才", "感性"],
  },
  {
    bgColor: "#6c2735",
    textColor: "#ffc053",
    dateText: "02.08",
    colorName: "勃艮第",
    text1: "善于模仿的恶作剧者",
    text2: ["热情", "可爱", "深思熟虑"],
  },
  {
    bgColor: "#ea4a6e",
    textColor: "#ffffff",
    dateText: "02.09",
    colorName: "紫红色",
    text1: "活跃，热血的人",
    text2: ["国际", "活跃", "领导者"],
  },
  {
    bgColor: "#ea618e",
    textColor: "#ffe933",
    dateText: "02.10",
    colorName: "玫瑰红",
    text1: "温柔，喜欢帮助和鼓励他人",
    text2: ["爱", "感性", "知性"],
  },
  {
    bgColor: "#d3336f",
    textColor: "#ffffff",
    dateText: "02.11",
    colorName: "红色调",
    text1: "坦率，总是发自内心的开心",
    text2: ["开放", "单纯明快", "表现力强"],
  },
  {
    bgColor: "#d5345e",
    textColor: "#ffffff",
    dateText: "02.12",
    colorName: "胭脂红",
    text1: "安静但积极的行动派",
    text2: ["外交", "热情", "激烈的感情"],
  },
  {
    bgColor: "#585b54",
    textColor: "#ffb033",
    dateText: "02.13",
    colorName: "莺色",
    text1: "注重培养自己价值观的艺术家",
    text2: ["上进", "心细", "上进"],
  },
  {
    bgColor: "#726d40",
    textColor: "#ffdb33",
    dateText: "02.14",
    colorName: "海松色",
    text1: "具有都市品味的人",
    text2: ["诚实", "气度", "威严"],
  },
  {
    bgColor: "#89c3eb",
    textColor: "#ffffff",
    dateText: "02.15",
    colorName: "勿忘草",
    text1: "三思而后行的慎重派",
    text2: ["友谊", "和平", "和谐"],
  },
  {
    bgColor: "#a4c1d7",
    textColor: "#ffffff",
    dateText: "02.16",
    colorName: "烟蓝色",
    text1: "不断提高自我的努力家",
    text2: ["谦虚", "踏实", "克己"],
  },
  {
    bgColor: "#4c5e74",
    textColor: "#ff979e",
    dateText: "02.17",
    colorName: "斯马尔托",
    text1: "对任何事物都很投入",
    text2: ["毅力", "完美主义", "品格"],
  },
  {
    bgColor: "#6c3524",
    textColor: "#ffaa57",
    dateText: "02.18",
    colorName: "巧克力",
    text1: "能正确主张自己的想法",
    text2: ["不屈的灵魂", "灵光一闪", "自我正当化"],
  },
  {
    bgColor: "#223a70",
    textColor: "#81aee0",
    dateText: "02.19",
    colorName: "藏青色",
    text1: "明确前方道路的有识之士",
    text2: ["大气", "领导者", "感性"],
  },
  {
    bgColor: "#fff1cf",
    textColor: "#ffb25f",
    dateText: "02.20",
    colorName: "蛋黄色",
    text1: "敢于创新的个性派",
    text2: ["迷人", "个性", "中庸"],
  },
  {
    bgColor: "#fff799",
    textColor: "#ffc514",
    dateText: "02.21",
    colorName: "室内灯",
    text1: "有强烈个性和主张的人",
    text2: ["魅惑", "个性", "节制"],
  },
  {
    bgColor: "#fabf14",
    textColor: "#f8ff82",
    dateText: "02.22",
    colorName: "郁金色",
    text1: "追求乐趣和新奇的乐观主义者",
    text2: ["敏感", "有趣", "艺术天赋"],
  },
  {
    bgColor: "#ffec47",
    textColor: "#ffa854",
    dateText: "02.23",
    colorName: "油菜花",
    text1: "让人欣喜若狂的行为群体",
    text2: ["人道主义", "不言而行", "浪漫主义"],
  },
  {
    bgColor: "#d8e2ae",
    textColor: "#ffffff",
    dateText: "02.24",
    colorName: "铅绿",
    text1: "总是抱着希望向前迈进的人",
    text2: ["放松", "善于社交", "积极向上"],
  },
  {
    bgColor: "#e5e8e1",
    textColor: "#b5cb97",
    dateText: "02.25",
    colorName: "雾白色",
    text1: "执着追求目标的人",
    text2: ["目的", "感动", "名誉"],
  },
  {
    bgColor: "#becebc",
    textColor: "#ffffff",
    dateText: "02.26",
    colorName: "叶子背面",
    text1: "对难题也不轻言放弃",
    text2: ["圆满", "努力", "正确"],
  },
  {
    bgColor: "#a1a46d",
    textColor: "#ffffff",
    dateText: "02.27",
    colorName: "柳茶",
    text1: "不受繁文缛节舒服之人",
    text2: ["愉快对话", "粗略", "开放"],
  },
  {
    bgColor: "#5f6527",
    textColor: "#ffcc5f",
    dateText: "02.28",
    colorName: "橄榄绿",
    text1: "重视与人交流",
    text2: ["感性", "踏实", "优雅"],
  },
  {
    bgColor: "#578a3d",
    textColor: "#fffc14",
    dateText: "02.29",
    colorName: "室内灯",
    text1: "照顾朋友的人",
    text2: ["道德", "智能", "构想"],
  },
  {
    bgColor: "#f5b199",
    textColor: "#e85566",
    dateText: "03.01",
    colorName: "一斤染",
    text1: "精力充沛的人，为他人注入活力",
    text2: ["责任心", "无忧无虑", "善良"],
  },
  {
    bgColor: "#fdede4",
    textColor: "#ff9a8d",
    dateText: "03.02",
    colorName: "婴儿粉",
    text1: "幸福家庭",
    text2: ["理想", "温馨", "包容"],
  },
  {
    bgColor: "#f4b3c2",
    textColor: "#ffffff",
    dateText: "03.03",
    colorName: "鸨色",
    text1: "被爱着就会美丽灿烂的人",
    text2: ["精神恋爱", "礼仪", "魅力"],
  },
  {
    bgColor: "#eb564e",
    textColor: "#ffffff",
    dateText: "03.04",
    colorName: "罂粟红",
    text1: "不满足于平均的人",
    text2: ["主角", "高贵", "敏感"],
  },
  {
    bgColor: "#cf0125",
    textColor: "#ffe7ca",
    dateText: "03.05",
    colorName: "樱桃红",
    text1: "脚踏实地的坚定者",
    text2: ["现实主义", "感性", "热情"],
  },
  {
    bgColor: "#fef4f4",
    textColor: "#ff9597",
    dateText: "03.06",
    colorName: "樱花色",
    text1: "隐藏着让人感动的力量",
    text2: ["爱情", "体贴", "健全"],
  },
  {
    bgColor: "#f3a68c",
    textColor: "#ffffff",
    dateText: "03.07",
    colorName: "橙红色",
    text1: "真心祝愿他人",
    text2: ["温柔", "关系", "感性"],
  },
  {
    bgColor: "#f2a0a1",
    textColor: "#ffffff",
    dateText: "03.08",
    colorName: "红梅色",
    text1: "充满爱的人",
    text2: ["爱情", "稳定的精神", "女人味"],
  },
  {
    bgColor: "#69821b",
    textColor: "#ffc674",
    dateText: "01.09",
    colorName: "苔藓绿",
    text1: "时常能感受到温暖的人",
    text2: ["匠心", "神秘", "想象力"],
  },
  {
    bgColor: "#7b8d42",
    textColor: "#78d3b0",
    dateText: "01.10",
    colorName: "草色",
    text1: "拥有广阔的情感世界",
    text2: ["智慧", "艺术", "精致"],
  },
  {
    bgColor: "#bdd99f",
    textColor: "#ffffff",
    dateText: "01.11",
    colorName: "雾绿",
    text1: "创造新时代的理想人物",
    text2: ["努力", "语言力", "勇气"],
  },
  {
    bgColor: "#d6e9ca",
    textColor: "#9c8e92",
    dateText: "01.12",
    colorName: "白绿",
    text1: "全力以赴的挑战者",
    text2: ["尊严", "外交", "洞察力"],
  },
  {
    bgColor: "#37a34a",
    textColor: "#fff68f",
    dateText: "01.13",
    colorName: "帕洛特绿",
    text1: "有自己生活方式的自立者",
    text2: ["语言行动力", "谦逊", "沉着冷静"],
  },
  {
    bgColor: "#7b8d44",
    textColor: "#e8c47f",
    dateText: "01.14",
    colorName: "草绿色",
    text1: "等待感情成熟的艺术家",
    text2: ["成熟", "感性"],
  },
  {
    bgColor: "#00552e",
    textColor: "#ffffff",
    dateText: "01.15",
    colorName: "深绿",
    text1: "瞳孔如星之羁绊",
    text2: ["信条", "模范", "慈爱"],
  },
  {
    bgColor: "#f0f6da",
    textColor: "#ff8697",
    dateText: "01.16",
    colorName: "白莉",
    text1: "在爱的实践中",
    text2: ["想象力", "追求自然"],
  },
  {
    bgColor: "#006e54",
    textColor: "#ffbc75",
    dateText: "01.17",
    colorName: "MOEGIIRO",
    text1: "有勇气和好奇心的美食家",
    text2: ["生活意识", "领导力", "微笑"],
  },
  {
    bgColor: "#47744b",
    textColor: "#96cd96",
    dateText: "01.18",
    colorName: "FOLIAGE",
    text1: "保持纯真少年",
    text2: ["诚实", "干练", "谦虚"],
  },
  {
    bgColor: "#9fc24d",
    textColor: "#ffffff",
    dateText: "01.19",
    colorName: "叶绿",
    text1: "坚持不懈的人",
    text2: ["温柔", "自尊", "精神"],
  },
  {
    bgColor: "#288c66",
    textColor: "#ebec90",
    dateText: "01.20",
    colorName: "森林绿",
    text1: "形象清晰者",
    text2: ["能量", "自我投资"],
  },
  {
    bgColor: "#a0d8ef",
    textColor: "#ff858b",
    dateText: "01.21",
    colorName: "天空色",
    text1: "感知美好事物的人",
    text2: ["感性", "可能性", "艺术性"],
  },
  {
    bgColor: "#00a3af",
    textColor: "#f1f49a",
    dateText: "01.22",
    colorName: "浅葱色",
    text1: "富有同情心",
    text2: ["兴奋", "爱情", "友情"],
  },
  {
    bgColor: "#38a1db",
    textColor: "#ffffff",
    dateText: "01.23",
    colorName: "露草",
    text1: "心境平和宁静",
    text2: ["年轻", "情绪", "专注力"],
  },
  {
    bgColor: "#00688b",
    textColor: "#ebec90",
    dateText: "01.24",
    colorName: "鸭羽色",
    text1: "快乐梦想的乐观者",
    text2: ["聪明", "诚实", "感性"],
  },
  {
    bgColor: "#0f2350",
    textColor: "#ff777e",
    dateText: "01.25",
    colorName: "深靛蓝",
    text1: "生活一帆风顺",
    text2: ["理想", "现实", "新生活"],
  },
  {
    bgColor: "#e3d7a3",
    textColor: "#ff9d4d",
    dateText: "01.26",
    colorName: "奶油",
    text1: "拥有太阳般的个性",
    text2: ["组织力", "机智", "表情丰富"],
  },
  {
    bgColor: "#fef400",
    textColor: "#83bc50",
    dateText: "01.27",
    colorName: "淡柠檬",
    text1: "优雅大气的人",
    text2: ["穿着", "神秘的睡眠"],
  },
  {
    bgColor: "#ffd900",
    textColor: "#ce8230",
    dateText: "01.28",
    colorName: "鸭羽色",
    text1: "天生的乐观者",
    text2: ["冒险", "开朗", "好奇心"],
  },
  {
    bgColor: "#c3d825",
    textColor: "#81a326",
    dateText: "01.29",
    colorName: "若草色",
    text1: "具有非凡说服力的人",
    text2: ["直觉", "名誉", "运动神经"],
  },
  {
    bgColor: "#529c47",
    textColor: "#fff333",
    dateText: "01.30",
    colorName: "淡柠檬",
    text1: "与动植物投缘的人",
    text2: ["充满爱", "喜爱动物"],
  },
  {
    bgColor: "#e0ebaf",
    textColor: "#fa9121",
    dateText: "01.31",
    colorName: "嫩芽色",
    text1: "脆弱的浪漫主义者",
    text2: ["感伤", "社会适应性"],
  },
];
